<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Language strings.
 *
 * @package    mod_iearchy
 * @copyright  2026
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['pluginname'] = 'Iearchy';
$string['modulename'] = 'Iearchy';
$string['modulenameplural'] = 'Iearchies';
$string['pluginadministration'] = 'Iearchy administration';
$string['privacy:metadata'] = 'The iearchy module stores organisational content inside the course module instance and no personal Moodle user data.';

$string['iearchy:addinstance'] = 'Add a new iearchy';
$string['iearchy:view'] = 'View iearchy';
$string['iearchy:managecontent'] = 'Manage iearchy content';

$string['defaultheadereyebrow'] = 'Our organisation';
$string['defaultheadertitle'] = 'Team';
$string['headereyebrow'] = 'Header eyebrow';
$string['headertitle'] = 'Header title';

$string['directory'] = 'Directory';
$string['viewdirectory'] = 'View directory';
$string['managelevels'] = 'Manage levels';
$string['manageemployees'] = 'Manage employees';
$string['backtodirectory'] = 'Back to directory';
$string['backtolevels'] = 'Back to levels';
$string['backtoemployees'] = 'Back to employees';

$string['addlevel'] = 'Add level';
$string['editlevel'] = 'Edit level';
$string['deletelevel'] = 'Delete level';
$string['levelsaved'] = 'Level saved.';
$string['leveldeleted'] = 'Level deleted.';
$string['confirmdeletelevel'] = 'Delete level "{$a}"?';
$string['levelhasemployees'] = 'Cannot delete level "{$a->title}" because it still contains {$a->count} employee(s).';
$string['nolevels'] = 'No visible levels have been configured yet.';
$string['nolevelsmanage'] = 'No levels have been created yet.';
$string['nolevelsforemployee'] = 'Create at least one level before adding employees.';
$string['levelnumber'] = 'Level {$a}';

$string['addemployee'] = 'Add employee';
$string['editemployee'] = 'Edit employee';
$string['deleteemployee'] = 'Delete employee';
$string['employeesaved'] = 'Employee saved.';
$string['employeedeleted'] = 'Employee deleted.';
$string['confirmdeleteemployee'] = 'Delete employee "{$a}"?';
$string['noemployees'] = 'No employees have been created yet.';

$string['eyebrow'] = 'Eyebrow';
$string['title'] = 'Title';
$string['level'] = 'Level';
$string['fullname'] = 'Full name';
$string['position'] = 'Position';
$string['description'] = 'Description';
$string['imageurl'] = 'Image URL';
$string['imagefile'] = 'Uploaded image';
$string['initials'] = 'Initials';
$string['sortorder'] = 'Sort order';
$string['visible'] = 'Visible';
$string['actions'] = 'Actions';
$string['employees'] = 'Employees';
$string['imageurl_help'] = 'Use a full external image URL or a Moodle file URL generated by the site.';
$string['invalidimageurl'] = 'Please enter a valid http(s) URL or a Moodle file URL (pluginfile.php/draftfile.php).';
$string['imagefile_help'] = 'Upload an image from Moodle files. If present, it is used before the external image URL.';
$string['initials_help'] = 'If the employee has no image, these initials are shown in the placeholder avatar.';
$string['missingavatarfallback'] = 'Provide initials if neither an uploaded image nor an image URL is set.';
$string['invalidlevel'] = 'Please select a valid level.';
$string['directoryempty'] = 'The iearchy will appear here once you add visible levels and employees.';
$string['openprofile'] = 'Open profile';
$string['close'] = 'Close';
$string['cardaria'] = '{$a->fullname}, {$a->position}';
$string['visibilityyes'] = 'Yes';
$string['visibilityno'] = 'No';
$string['dragdrophelp'] = 'Drag items to change their priority order.';
$string['priority'] = 'Priority';
$string['moveup'] = 'Move up';
$string['movedown'] = 'Move down';

$string['displaymode'] = 'Display mode';
$string['displaymode_help'] = 'Page: students open the activity to see the directory (like Page). Text/Media on course: HTML is shown inside the course section with no activity link (like Label).';
$string['displaymode_page'] = 'Page (like mod_page)';
$string['displaymode_inline'] = 'Text/Media on course (like mod_label)';
$string['invaliddisplaymode'] = 'Invalid display mode selected.';
$string['contentsection'] = 'Content for course page';
$string['content'] = 'Page content';
$string['content_help'] = 'Used for Text/Media on course mode (and can hold embedded files). For Page mode, this content is not shown on the course listing; use the description above if needed.';
